Create poetry example (#32)
* Create poetry examples

* WIP: update poetry install package example.

* Create example for installing dependencies

* Create upload package example for Poetry

* Add new line at end of file

* Poetry is included with the image

* Tweaking examples and adding tests

* Add description to upload example

* Add test-set_env_vars_for_poetry to jobs

* Tweak poetry command

* Tweak bash script for Poetry Command

* Remove trailing spaces

* Add space to if statement

* Remove $'s

* Update poetry parameters

* Update repo name

* Add verbose mode

* test upload package example for poetry

* Create simple package for twine, poetry and cli

* Call poetry upload example in test

* Rename test package

* Revert back to simplepkg-py

* Tweak poetry upload test

* Fix indentation

* Update poetry command

* Update poetry auth params

* Update toml file

* Update toml file

* Update poetry upload example

* Update directory

* check that poetry-package location

* Update poetry install example

* Update commands

* Update poetry install example

* Remove lock command

* Remove version

* Revert to previous approach

* Add description and author

* Change package version

* Change order of tests and update url

* Update poetry install command

* Add simplepkg

* Update poetry install test

* Add a package to the toml file

* Include package version

* Try requests library

* Remove lock

* Try verbose mode for debugging issue

* Try making library install more verbose

* Remove authentication

* Add authentication back in and remove poetry shell

* Update commands

* Remove add simplepkg

* Update command naming and remove poetry add command

* cd into poetry package

* Refactor tests

* Update examples to reflect changes

* Update src/commands/set_env_vars_for_poetry.yml

Co-authored-by: robertboulton <robert.boulton@ft.com>

* Update src/examples/poetry_install_packages.yml

Co-authored-by: robertboulton <robert.boulton@ft.com>

* Update example

* Update source url label and remove upload command

* Remove superfluous directory block

* Add comments to explain arbitrary label cloudsmith-source-url

* Remove redundant packages

* Move comment to the description section

* Move comments to the description section

* Remove white space

* Add poetry dependency

* Add lock argument

* Add -q switch

* Add poetry show

* Update poetry install example

* Update .circleci/test-deploy.yml

Co-authored-by: robertboulton <robert.boulton@ft.com>

* Update src/examples/poetry_install_packages.yml

Co-authored-by: robertboulton <robert.boulton@ft.com>

* Update src/examples/upload_package_using_poetry.yml

Co-authored-by: robertboulton <robert.boulton@ft.com>

* Update src/scripts/set_env_vars_for_poetry.sh

Co-authored-by: robertboulton <robert.boulton@ft.com>

* Update src/examples/poetry_install_packages.yml

Co-authored-by: robertboulton <robert.boulton@ft.com>

* Update src/scripts/set_env_vars_for_poetry.sh

Co-authored-by: robertboulton <robert.boulton@ft.com>

* Remove test blocks

* Update orb version

* Update simplepkg version

---------

Co-authored-by: robertboulton <robert.boulton@ft.com>

diff --git a/.circleci/test-deploy.yml b/.circleci/test-deploy.yml
--- a/.circleci/test-deploy.yml
+++ b/.circleci/test-deploy.yml
@@ -81,12 +81,73 @@ jobs:
             verify_ssl = true
             name = "cloudsmith"
             [packages]
-            simplepkg = "0.0.1"
+            simplepkg = "0.4.3"
             [requires]
             python_version = "3.9"
             EOT
       - run: pipenv install
 
+  test-set_env_vars_for_poetry:
+    docker:
+      - image: cimg/python:3.9
+    resource_class: small
+    steps:
+      - checkout
+      - cloudsmith-python/set_env_vars_for_poetry:
+          repository: "circleci-orb-testing"
+      - run:
+          name: Assert environment variables have been set
+          command: |
+            if [ $CLOUDSMITH_POETRY_USERNAME != "circleci-orb-testing" ]
+            then
+              echo "Test failed: CLOUDSMITH_POETRY_USERNAME has not been set correctly."
+              exit 1
+            fi
+            if [ -z $CLOUDSMITH_POETRY_PASSWORD ]
+            then
+              echo "Test failed: CLOUDSMITH_POETRY_PASSWORD has not been set."
+              exit 1
+            fi
+            echo "All tests passed."
+
+  test-upload_package_using_poetry:
+    docker:
+      - image: cimg/python:3.9
+    resource_class: small
+    steps:
+      - checkout
+      - cloudsmith-python/set_env_vars_for_poetry:
+          repository: circleci-orb-testing
+      - run:
+          # cloudsmith-source-url is an arbitrary label for the Cloudsmith Source URL
+          name: Create Poetry package and publish package
+          command: |
+            poetry new poetry-package
+            cd poetry-package
+            poetry source add --priority=default cloudsmith-source-url https://python.cloudsmith.io/financial-times/circleci-orb-testing/
+            poetry config http-basic.cloudsmith-source-url $CLOUDSMITH_POETRY_USERNAME $CLOUDSMITH_POETRY_PASSWORD
+            poetry build
+            poetry publish -r cloudsmith-source-url
+
+  test-poetry_install_packages_example:
+    docker:
+      - image: cimg/python:3.9
+    steps:
+      - checkout
+      - cloudsmith-python/set_env_vars_for_poetry:
+          repository: circleci-orb-testing
+      - run:
+          # cloudsmith-source-url is an arbitrary label for the Cloudsmith Source URL
+          name: Create Poetry package and install dependencies
+          command: |
+            poetry new poetry-package
+            cd poetry-package
+            poetry source add --priority=default cloudsmith-source-url https://packages.ft.com/basic/circleci-orb-testing/python/simple/
+            poetry config http-basic.cloudsmith-source-url $CLOUDSMITH_POETRY_USERNAME $CLOUDSMITH_POETRY_PASSWORD
+            poetry add -q simplepkg
+            poetry install
+            poetry show
+            
   test-configure_pip_example:
     docker:
       - image: cimg/python:3.9
@@ -189,6 +250,12 @@ workflows:
       - test-pipenv_install_package_example:
           context: circleci-orb-publishing
           filters: *filters
+      - test-set_env_vars_for_poetry:
+          context: circleci-orb-publishing
+          filters: *filters
+      - test-poetry_install_packages_example:
+          context: circleci-orb-publishing
+          filters: *filters
       - test-configure_pip_example:
           context: circleci-orb-publishing
           filters: *filters
@@ -203,6 +270,10 @@ workflows:
           filters: *filters
           requires:
             - test-upload_package_using_twine
+      - test-upload_package_using_poetry:
+          context: circleci-orb-publishing
+          filters: *filters
+
       # The orb must be re-packed for publishing, and saved to the workspace.
       - orb-tools/pack:
           filters: *release-filters
@@ -217,10 +288,13 @@ workflows:
             - test-pip_install_package_example
             - test-pip_install_requirements_example
             - test-pipenv_install_package_example
+            - test-set_env_vars_for_poetry
+            - test-poetry_install_packages_example
             - test-configure_pip_example
             - test-set_env_vars_for_twine
             - test-upload_package_using_twine
             - test-upload_package_using_cli
+            - test-upload_package_using_poetry
           # Use a context to hold your publishing token.
           context: circleci-orb-publishing
           filters: *release-filters
