Tweaking examples and adding tests

diff --git a/.circleci/test-deploy.yml b/.circleci/test-deploy.yml
--- a/.circleci/test-deploy.yml
+++ b/.circleci/test-deploy.yml
@@ -87,6 +87,61 @@ jobs:
             EOT
       - run: pipenv install
 
+  test-set_env_vars_for_poetry:
+    docker:
+      - image: cimg/python:3.9
+    resource_class: small
+    steps:
+      - checkout
+      - cloudsmith-python/set_env_vars_for_poetry:
+          repository: "circleci-orb-testing"
+      - run:
+          name: Assert environment variables have been set
+          command: |
+            if [ $CLOUDSMITH_USERNAME != "circleci-orb-testing"]
+            then
+              echo "Test failed: $CLOUDSMITH_USERNAME has not been set correctly."
+              exit 1
+            fi
+            if [ -z $CLOUDSMITH_PASSWORD ]
+            then
+              echo "Test failed: $CLOUDSMITH_PASSWORD has not been set."
+              exit 1
+            fi
+            echo "All tests passed."
+
+  test-poetry_install_packages_example:
+    docker:
+      - image: cimg/python:3.9
+    steps:
+      - checkout
+      - cloudsmith-python/set_env_vars_for_poetry:
+          repository: your-repository-id
+      - run:
+          name: Create pyproject.toml file
+          command: |
+            cat \<< EOT >> pyproject.toml
+            [tool.poetry]
+            name = "poetry-example"
+            version = "0.1.0"
+
+            [tool.poetry.dependencies]
+            python = "^3.9.0"
+            simplepkg = "^0.0.1"
+
+            [[tool.poetry.source]]
+            name = "cloudsmith"
+            url = "https://packages.ft.com/basic/financial-times-internal-releases/python/simple/"
+            priority = "default"
+
+            [build-system]
+            requires = ["poetry-core"]
+            build-backend = "poetry.core.masonry.api"
+            EOT
+      - run: >-
+          poetry config http-basic.your-repository-id $CLOUDSMITH_USERNAME $CLOUDSMITH_PASSWORD
+          poetry install
+
   test-configure_pip_example:
     docker:
       - image: cimg/python:3.9
@@ -189,6 +244,9 @@ workflows:
       - test-pipenv_install_package_example:
           context: circleci-orb-publishing
           filters: *filters
+      - test-poetry_install_packages_example:
+          context: circleci-orb-publishing
+          filters: *filters
       - test-configure_pip_example:
           context: circleci-orb-publishing
           filters: *filters
@@ -217,6 +275,8 @@ workflows:
             - test-pip_install_package_example
             - test-pip_install_requirements_example
             - test-pipenv_install_package_example
+            - test-set_env_vars_for_poetry
+            - test-poetry_install_packages_example
             - test-configure_pip_example
             - test-set_env_vars_for_twine
             - test-upload_package_using_twine
